package com.securebank.common.domain.error;

public enum ErrorCode {
    ACCESS_DENIED,
    ACCOUNT_NOT_FOUND,
    ACCOUNT_BLOCKED,
    ACCOUNT_CLOSED,
    INSUFFICIENT_BALANCE,
    INVALID_TRANSACTION,
    DUPLICATE_REQUEST,
    IDEMPOTENCY_KEY_CONFLICT,
    TENANT_ACCESS_DENIED,
    TRANSACTION_NOT_FOUND,
    INVALID_STATE_TRANSITION,
    CUSTOMER_NOT_FOUND,
    VALIDATION_ERROR,
    CURRENCY_MISMATCH,
    LEDGER_IMBALANCE,
    UNAUTHENTICATED,
    INTERNAL_ERROR
}
