server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: account-service
  datasource:
    url: ${ACCOUNT_DB_URL:jdbc:postgresql://localhost:5432/account_db}
    username: ${DB_USERNAME:banking}
    password: ${DB_PASSWORD:banking}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER:http://localhost:8085/realms/banking}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318/v1/traces}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} trace=%X{traceId:-} span=%X{spanId:-} tenant=%X{tenantId:-} user=%X{userId:-} service=${spring.application.name} %5p %m%n"
